site_name: Habit Tracker
site_description: A simple habit tracker application

theme:
  name: material
  language: it
  palette:
    scheme: slate
    primary: indigo

nav:
  - Home: index.md
  - Setup: setup.md
  - Changelog: changelog.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format